name: Publish Docker image

on:
  push:
    branches:
      - prod
      - staging
    tags:
      - 'v*'

jobs:
  docker:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/tietokilta/ilmomasiina
          flavor: |
            latest=${{ github.ref == 'refs/heads/prod' }}
          tags: |
            type=semver,pattern={{version}},enable=${{ github.ref_type == 'tag' }}
            type=ref,event=branch,enable=${{ github.ref_type == 'branch' }}
            type=sha
      -
        name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BRANDING_HEADER_TITLE_TEXT=Tietokillan ilmomasiina
            BRANDING_FOOTER_GDPR_TEXT=Tietosuoja
            BRANDING_FOOTER_GDPR_LINK=https://tietokilta.fi/kilta/hallinto/viralliset-asiat/rekisteriselosteet/
            BRANDING_FOOTER_HOME_TEXT=Tietokilta.fi
            BRANDING_FOOTER_HOME_LINK=https://tietokilta.fi

  npm:
    name: Publish JS packages
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Install dependencies
        run: |
          npm install -g pnpm@7
          pnpm install --frozen-lockfile
      -
        name: Build packages
        run: pnpm run --filter @tietokilta/ilmomasiina-models build
      -
        name: Publish to NPM
        run: pnpm publish --filter @tietokilta/ilmomasiina-models --no-git-checks
      -
        name: Publish to GitHub Packages
        run: |
          npm set @tietokilta:registry https://npm.pkg.github.com/
          pnpm publish --filter @tietokilta/ilmomasiina-models --no-git-checks

  deploy:
    name: Push update to App Service
    needs: docker
    if: github.ref_type == 'branch'
    runs-on: ubuntu-latest
    environment: production
    steps:
    -
      name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    -
      uses: azure/webapps-deploy@v2
      with:
        app-name: tik-ilmo-${{ github.ref_name }}-app
        images: 'ghcr.io/tietokilta/ilmomasiina:${{ github.ref_name }}'
